name: ren
channels:
  - pytorch
  - nvidia
  - conda-forge
  - robostack
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - cudatoolkit-dev=11.3.1
  - setuptools=59.5.0
  - python=3.8
  - pip=21.3.1
  - easydict=1.9
  - numpy=1.21.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - tensorboard=2.6.0
  - pytorch-lightning=1.4.9
  - torchmetrics=0.6.2
  - hdf5plugin==3.2.0
  - h5py==3.1.0
  - ros-noetic-rosbag=1.15.9
  - absl-py=1.1.0
  - opencv=4.5.2              # Matches existing ESIM C++ OpenCV version for 
                              # identical imread() RGB-to-grayscale behaviour
  - pip:
    - roma==1.2.7
    - lpips==0.1.4
    - nerfacc==0.3.1
    - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
